project:
  type: website

website:
  title: "Haley and Bella's Wedding"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: about.qmd
        text: Information
      - href: survey.qmd
        text: RSVP

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

